Repository Compete-McGill/wisp-users-microservice, pull requests merged in 2020-06, with the labels that each got.

#22 Feature/username email verification
  docker-compose.yaml
  src/server.ts
  src/validators/user.ts
  src/validators/userCustom.ts
Labels: bug

#23 Features/unit tests
  .github/workflows/checks.yaml
  .gitignore
  .nycrc.json
  docker-compose.test.yaml
  package-lock.json
  package.json
  src/controllers/auth.ts
  src/controllers/user.ts
  src/validators/userCustom.ts
  tests/unit/config/config.test.ts
  tests/unit/controllers/auth.test.ts
  tests/unit/controllers/user.test.ts
  tests/unit/stubs/auth.ts
  tests/unit/stubs/user.ts
  tests/unit/util/codeforces.test.ts
  tsconfig.json
Labels: enhancement

#29 Implement linting
  .eslintrc.js
  .github/workflows/checks.yaml
  .prettierrc.js
  package-lock.json
  package.json
  src/app.ts
  src/config/bcrypt.ts
  src/config/errorFormatter.ts
  src/config/errorLogger.ts
  src/config/logger.ts
  src/config/requestLogger.ts
  src/config/statusCodes.ts
  src/controllers/auth.ts
  src/controllers/user.ts
  src/database/interactions/user.ts
  src/database/models/user.ts
  src/routes/auth.ts
  src/routes/user.ts
  src/server.ts
  src/util/codeforces.ts
  src/validators/auth.ts
  src/validators/user.ts
  src/validators/userCustom.ts
  tests/unit/config/config.test.ts
  tests/unit/controllers/auth.test.ts
  tests/unit/controllers/user.test.ts
  tests/unit/stubs/auth.ts
  tests/unit/stubs/user.ts
  tests/unit/util/codeforces.test.ts
  tests/utils/consts/validation.ts
  tslint.json
Labels: enhancement

#31 0.1.1
  .eslintrc.js
  .github/workflows/checks.yaml
  .gitignore
  .nycrc.json
  .prettierrc.js
  docker-compose.test.yaml
  docker-compose.yaml
  package-lock.json
  package.json
  src/app.ts
  src/config/bcrypt.ts
  src/config/errorFormatter.ts
  src/config/errorLogger.ts
  src/config/logger.ts
  src/config/requestLogger.ts
  src/config/statusCodes.ts
  src/controllers/auth.ts
  src/controllers/user.ts
  src/database/interactions/user.ts
  src/database/models/user.ts
  src/routes/auth.ts
  src/routes/user.ts
  src/server.ts
  src/util/codeforces.ts
  src/validators/auth.ts
  src/validators/user.ts
  src/validators/userCustom.ts
  tests/unit/config/config.test.ts
  tests/unit/controllers/auth.test.ts
  tests/unit/controllers/user.test.ts
  tests/unit/stubs/auth.ts
  tests/unit/stubs/user.ts
  tests/unit/util/codeforces.test.ts
  tests/utils/consts/validation.ts
  tsconfig.json
  tslint.json
Labels: bug, enhancement

#33 Features/reset lastsubmissions route
  src/controllers/user.ts
  src/database/interactions/user.ts
  src/routes/user.ts
  tests/unit/controllers/user.test.ts
  tests/unit/stubs/user.ts
Labels: enhancement

#35 Bugfixes/default values for user model
  src/database/models/user.ts
Labels: bug

#36 Features/move to helm charts
  chart/wisp-users/.helmignore
  chart/wisp-users/Chart.yaml
  chart/wisp-users/templates/NOTES.txt
  chart/wisp-users/templates/_helpers.tpl
  chart/wisp-users/templates/configmap.yaml
  chart/wisp-users/templates/deployment.yaml
  chart/wisp-users/templates/service.yaml
  chart/wisp-users/templates/tests/test-connection.yaml
  chart/wisp-users/values.yaml
  docker-compose.yaml
Labels: enhancement
